### ISSUE TITLE
Legacy generator support

### ISSUE THREAD

**Issue by neclimdul** [Chi-teck/drupal-code-generator#104]
Is there a way of a project supporting DCG 3 and DCG 2 generators in the same version? 

Looking at the 3.0.0 release notes it looks the answer currently might be no. However if a module is trying to support both Drush 11 and 12, and generators aren't your primary feature just a convenience, it makes maintenance a lot more difficult having to maintain two parallel versions. Maybe there's a way to provide a BC or FC layer to support the transition?

**Comment by Chi-teck** [comment]
In Drush 12 generators are registered in a different way.
So you can create new generators without removing legacy ones.

See for details https://github.com/drush-ops/drush/issues/5600

**Comment by neclimdul** [comment]
Cool, I see if I can make that work. Thanks!

**Comment by neclimdul** [comment]
Ok, I think I found the real problem. Reading the related pull request that seems to deal generators that are tagged onto the service container but that's not the whole solution because Drush seems to actually auto-detects generators as well. 

There's some code in the generator detection that tries to filter these classes using class_exists but that runs a bit late because the ApplicationFactory is trying to reflect on the class before that code runs.

I'll open a PR with possible fix:

Crash log:
```
Error: Class "DrupalCodeGenerator\Command\ModuleGenerator" not found in /app/vendor/weitzman/drupal-test-traits/src/Drush/Generators/ExistingGenerator.php on line 10 #0 /app/vendor/composer/ClassLoader.php(582): include()
#1 /app/vendor/composer/ClassLoader.php(433): Composer\Autoload\{closure}('/app/vendor/com...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('weitzman\\Drupal...')
#3 /app/vendor/drush/drush/src/Runtime/ServiceManager.php(204): ReflectionClass->__construct('weitzman\\Drupal...')
#4 [internal function]: Drush\Runtime\ServiceManager->Drush\Runtime\{closure}('weitzman\\Drupal...')
#5 /app/vendor/drush/drush/src/Runtime/ServiceManager.php(209): array_filter(Array, Object(Closure))
#6 /app/vendor/drush/drush/src/Commands/generate/ApplicationFactory.php(59): Drush\Runtime\ServiceManager->discoverPsr4Generators()
#7 /app/vendor/drush/drush/src/Commands/generate/ApplicationFactory.php(38): Drush\Commands\generate\ApplicationFactory->discover()
#8 /app/vendor/drush/drush/src/Commands/generate/GenerateCommands.php(60): Drush\Commands\generate\ApplicationFactory->create()
#9 [internal function]: Drush\Commands\generate\GenerateCommands->generate('drush-command-f...', Array)
#10 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(276): call_user_func_array(Array, Array)
#11 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#12 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#13 /app/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(391): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#14 /app/vendor/symfony/console/Command/Command.php(326): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /app/vendor/symfony/console/Application.php(1081): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /app/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /app/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /app/vendor/drush/drush/src/Runtime/Runtime.php(110): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /app/vendor/drush/drush/src/Runtime/Runtime.php(40): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /app/vendor/drush/drush/drush.php(139): Drush\Runtime\Runtime->run(Array)
#21 /app/vendor/drush/drush/drush(4): require('/app/vendor/dru...')
#22 /app/vendor/bin/drush(119): include('/app/vendor/dru...')
#23 {main}
```

**Comment by neclimdul** [comment]
created that drush bug. Think this can be closed.
