### ISSUE TITLE
Drupal 10, Drush 11 compatibility with Drupal Code Generator

### ISSUE THREAD

**Issue by jameswilson** [Chi-teck/drupal-code-generator#96]
Drush 11.5.1  still requires chi-teck/drupal-code-generator ^2.4

But when I try to use `drush generate`, it is broken.

I tried to require chi-teck/drupal-code-generator ^3,  but it conflicts with drush requirements.

Is there any suggested path that works right now for Drupal 10 with Drush 11?

```
❯ ddev drush generate theme
 [warning] Undefined variable $container ApplicationFactory.php:74
TypeError: DrupalCodeGenerator\Helper\DrupalContext::__construct(): Argument #1 ($container) must be of type Symfony\Component\DependencyInjection\ContainerInterface, null given, called in /var/www/html/vendor/drush/drush/src/Commands/generate/ApplicationFactory.php on line 74 in /var/www/html/vendor/chi-teck/drupal-code-generator/src/Helper/DrupalContext.php on line 43 #0 /var/www/html/vendor/drush/drush/src/Commands/generate/ApplicationFactory.php(74): DrupalCodeGenerator\Helper\DrupalContext->__construct(NULL)
#1 /var/www/html/vendor/drush/drush/src/Commands/generate/GenerateCommands.php(52): Drush\Commands\generate\ApplicationFactory->create()
#2 [internal function]: Drush\Commands\generate\GenerateCommands->generate('theme', Array)
#3 /var/www/html/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#4 /var/www/html/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#5 /var/www/html/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#6 /var/www/html/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(390): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#7 /var/www/html/vendor/symfony/console/Command/Command.php(312): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/vendor/drush/drush/src/Runtime/Runtime.php(124): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/vendor/drush/drush/src/Runtime/Runtime.php(51): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/vendor/drush/drush/drush.php(77): Drush\Runtime\Runtime->run(Array)
#14 /var/www/html/vendor/drush/drush/drush(4): require('/var/www/html/v...')
#15 /var/www/html/vendor/bin/drush(120): include('/var/www/html/v...')
#16 {main}
TypeError: DrupalCodeGenerator\Helper\DrupalContext::__construct(): Argument #1 ($container) must be of type Symfony\Component\DependencyInjection\ContainerInterface, null given, called in /var/www/html/vendor/drush/drush/src/Commands/generate/ApplicationFactory.php on line 74 in DrupalCodeGenerator\Helper\DrupalContext->__construct() (line 43 of /var/www/html/vendor/chi-teck/drupal-code-generator/src/Helper/DrupalContext.php).
 [warning] Drush command terminated abnormally.
Failed to execute command drush generate theme: exit status 1```

**Comment by Chi-teck** [comment]
DCG 2 works well with Drupal 11 and Drupal 10 on my localhost. I think the issue is specific to your local environment.
Seems like Drupal bootstrap process failed.

As for DCG 3. The work is in progress (https://github.com/drush-ops/drush/pull/5371). You can install that branch with the following command.
```
composer require "drush/drush" "dev-dcg-3 as 11.5.1" -W
```

**Comment by jameswilson** [comment]
Thank you. You may be correct.  This is the first multi-site I've worked on in a long time and I'm definitely seeing other issues running drush commands with site aliases and/or --uri options. Many things are not working correctly.  I need to read up some more and will update here if I find a resolution that works explicitly

**Comment by jameswilson** [comment]
So the solution is that I must use `--uri` or a properly configured drush alias (even though the default site is in sites/default/ folder.  I suppose this is fair and to be expected because I'm using the sites/sites.php file to define the mappings from domain names to site folders.

Anyway, I do see a "no-ansi" warning, but this doesn't prevent it from working.

```
❯ ddev drush generate theme --uri=multisite-example.ddev.site
 [warning] Undefined array key "no-ansi" GenerateCommands.php:76

 Welcome to theme generator!
–––––––––––––––––––––––––––––

 Theme name [Docroot]:
```

```
❯ ddev drush @multisite-example.ddev generate theme
 [warning] Undefined array key "no-ansi" GenerateCommands.php:76

 Welcome to theme generator!
–––––––––––––––––––––––––––––

 Theme name [Docroot]:
 ➤
```

Apologies on my goof here.

**Comment by Chi-teck** [comment]
Actually "no-ansi" warning is a known issue.
https://github.com/drush-ops/drush/pull/5371/files#diff-f434a2d9436a53f74041f271533edee490c4b96a8b488368f240b1b1cc07df5dR90

**Comment by weitzman** [comment]
It does work when you use that --no-ansi option in Drush. I think it might get added as a negation of --no-ansi. Not sure. Seems fine for DCG to add it on own application if needed.
